version: '3.8'

services:
  meetbot:
    build: .
    shm_size: '2gb'
    volumes:
      # Save recordings directly to Windows folder
      - ./recordings:/app/recordings
      - ./user_data:/app/user_data
    environment:
      - DISPLAY=:99
      - PULSE_SERVER=unix:/var/run/pulse/native
